### ISSUE TITLE
mstsca_interop 没法还原 

### ISSUE THREAD

**Issue by huxiaozhong** [BlazorPlus/BlazorCefApp#1]
这是个啥东西，提示黄色叹号 编译不通过 好多错误  咋解决

**Comment by BlazorPlus** [comment]
> 
> 
> 这是个啥东西，提示黄色叹号 编译不通过 好多错误 咋解决

@huxiaozhong 

从 /dllrefs/ 文件夹里获取.   这是为后来的例子准备的.  

才发现VS没有自动引用它,  晚点我把它打包进nuget以杜绝这种问题.

**Comment by BlazorPlus** [comment]
发现是 csproj 文件里直接对 D:\temp\ 的文件进行绝对路径的引用了. 
已修正为相对引用.

**Comment by huxiaozhong** [comment]
谢谢
